language: scala

scala:
  - 2.10.6
  - 2.11.8

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

matrix:
  include:
  - scala: 2.12.0-RC2
    jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

install:
  - pip install --user codecov

script:
  - if [[ "$TRAVIS_JDK_VERSION" == *jdk8* ]] && [[ "$TRAVIS_SCALA_VERSION" == 2.11.* ]];
      then
        sbt ++$TRAVIS_SCALA_VERSION clean validateJVM coverage coverageReport &&
        sbt ++$TRAVIS_SCALA_VERSION coverageAggregate &&
        codecov;
      else
        sbt ++$TRAVIS_SCALA_VERSION clean core/test tests/test scalaz/test &&
        sbt ++$TRAVIS_SCALA_VERSION tests/it:test monix/it:test scalaz/it:test;
    fi;

  # See http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
